### ISSUE TITLE
Bug: Remove VerifyLLDPNeighbors Failure Message Newlines

### ISSUE THREAD

**Issue by kpbush30** [aristanetworks/anta#816]
Identified this bug through the use of AVD validate state, when `VerifyLLDPNeighbors` connectivity test fails, the reporting markdown is broken due to new lines injected into table.

This could be solved in AVD by stripping newline before placing in report, but verified the failure message for `VerifyLLDPNeighbors` is not consistent with other ANTA failures. Looks like fix is to return failures list of dicts similar to `VerifyReachability`.

https://github.com/aristanetworks/anta/blob/main/anta/tests/connectivity.py#L173-L179

**Comment by gmuloc** [comment]
Hi @kpbush30 I think this may be a duplicate from https://github.com/aristanetworks/anta/issues/752 
Can you confirm if upgrading AVD solves your issue?

**Comment by kpbush30** [comment]
@gmuloc - you are right, my mistake, my environment had downgraded to 4.8.0. Validated this is fixed 4.10.0
 
Apologies, ahank you for the response!
