### ISSUE TITLE
fix: `routing.bgp.VerifyBGPPeersHealth` fails when a BGP message queue is not empty.

### ISSUE THREAD

**Issue by mtache** [aristanetworks/anta#890]
Today, [VerifyBGPPeersHealth](https://anta.arista.com/stable/api/tests.routing.bgp/#anta.tests.routing.bgp.VerifyBGPPeersHealth) has been designed to fail when a BGP message queue is not empty.

This situation is not necessarily an issue in a production deployment. A BGP message queue can have a transient state of messages waiting to be sent to a peer.

Possible solutions discussed with SE/AS:
- Set VerifyBGPPeersHealth state to SUCCESS with a message if BGP message queues are not empty
- Introduce a WARNING test state
- Add a test input to let the user decide the SUCCESS/FAILURE/WARNING test state with a configurable threshold

**Comment by carl-baillargeon** [comment]
Added the `check_tcp_queues` knob in #888

https://anta.arista.com/main/api/tests.routing.bgp/#anta.tests.routing.bgp.VerifyBGPSpecificPeers
