### ISSUE TITLE
Running BGP health test on switch wihthout multi-agent 

### ISSUE THREAD

**Issue by kosichd** [aristanetworks/anta#943]
On switches that do not have "service routing protocols model multi-agent" configured, the cmd "show bgp {afi} {safi} summary  is not supported. When using VerifyBGPSpecificPeers or VerifyBGPHealth tests, it seems to only work if the switch in question is using mulit-agent. For switches that have "service routing protocols model ribd" configured, there should be a way for the test to run "show ip bgp sum' 

It seems the problem may be here, as "show bgp {afi} sum' is not a valid EOS command:

    commands: ClassVar[list[AntaCommand | AntaTemplate]] = [
        AntaTemplate(template="show bgp {afi} {safi} summary vrf {vrf}", revision=3),
        AntaTemplate(template="show bgp {afi} summary", revision=3),

From a switch running 4.31.5M, '**summary**' is not an option

switch#sh bgp ipv4 ?
  access-list      Named access-list
  labeled-unicast  Display labeled-unicast information
  multicast        Display multicast information
  unicast          Display unicast information

Also from a switch not running multi-agent:

switch#sh bgp ipv4 unicast sum
**% Not supported**

**Comment by carl-baillargeon** [comment]
Hi @kosichd,

These tests are indeed only supported on switches running with `multi-agent`. Multi-agent has been the default since 4.30.1, and starting with 4.32, you cannot configure `ribd` at all. Therefore, we don't have any plans to support `ribd` for these tests.

The `show bgp {afi} summary` command template is only used when the AFI is *not* IPv4 or IPv6 (e.g., evpn, vpn-ipv4, etc.). VRF is not needed here since these AFIs operate at a global level and do not use the VRF concept in the same way as IPv4/IPv6. On the other hand, `show bgp {afi} {safi} summary vrf {vrf}` template is used with IPv4 and IPv6 AFIs, where a SAFI is also needed with an optional VRF.

We have simpified the logic of this in PR #888, where we now use `show bgp summary vrf all` and `show bgp neighbors vrf all` commands instead, without impacting test inputs.

**Comment by kosichd** [comment]
Thanks for the quick reply @carl-baillargeon

**Comment by carl-baillargeon** [comment]
Anytime @kosichd. I will add a note in our documentation around this.

Thanks!

**Comment by gmuloc** [comment]
The goal for this one would be to write two new tests in parallel of `VerifyBGPSpecificPeers` or `VerifyBGPPeersHealth` tailored for RIBD with new names (because they require different commands).

The documentation warning needs to be updated

**Comment by gmuloc** [comment]
@kosichd please give these new tests a run and lets us know if that works for you! You need to install ANTA from main.

**Comment by kosichd** [comment]
Hi @gmuloc the below works:


    anta.tests.routing:
      bgp:
        - VerifyBGPPeerSessionRibd:
            check_tcp_queues: false
            bgp_peers:
              - peer_address:  1.1.1.1
                vrf: default

But does the neighbor have to be explicitly defined? Or can you just specify the VRF like in VerifyBGPPeersHealth and have it check all neighbors in that VRF? 

anta.tests.routing:
  bgp:
    - VerifyBGPPeersHealth:
        address_families:
          - afi: "evpn"
          - afi: "ipv4"
            safi: "unicast"
            vrf: "default"
          - afi: "ipv6"
            safi: "unicast"
            vrf: "DEV"
            check_tcp_queues: false

**Comment by kosichd** [comment]
@gmuloc  is this the syntax for the new VerifyBGPPeersHealthRibd test? 

    - VerifyBGPPeersHealthRibd:
        address_families:
          - afi: "ipv4"
            safi: "unicast"
            vrf: "default"

**Comment by gmuloc** [comment]
> [@gmuloc](https://github.com/gmuloc) is this the syntax for the new VerifyBGPPeersHealthRibd test?
> 
> ```
> - VerifyBGPPeersHealthRibd:
>     address_families:
>       - afi: "ipv4"
>         safi: "unicast"
>         vrf: "default"
> 
>      **VerifyBGPPeersHealthRibd test inputs are not valid: 1 validation error for Input                                                                                                                                                                                                      
>                         address_families**    
> ```


You can find the test documentation in the `main` doc on the website:

https://anta.arista.com/main/api/tests.routing.bgp/#anta.tests.routing.bgp.VerifyBGPPeersHealthRibd

you cannot give address families for ribd, nor any specific VRF - maybe this test can be augmented to filter on specific VRFs

**Comment by kosichd** [comment]
I understand now, thanks @gmuloc. Thanks to the ANTA team for implementing!
