### ISSUE TITLE
VerifyEVPNType2Route test fails for locally originated MAC/IP addresses

### ISSUE THREAD

**Issue by Gandalf2110** [aristanetworks/anta#950]
The 'VerifyEVPNType2Route' test currently marks endpoints with locally originated MAC/IP addresses as "FAILURE.

This behavior is unexpected because locally originated entries:
1. Are valid endpoints that can exist in the database of a VTEP.
2. Can still be advertised correctly to other VTEPs.

Marking these as "FAILURE" results in misleading test outcomes, especially when specific endpoints are explicitly validated and when the 'leaf' tag is applied to include all leaf devices in test.

Output of entry that contain locally originated mac-ip:

```VerifyEVPNType2Route is FAILURE for Leaf-01 with Message: The following EVPN Type-2 routes do not have at least one valid and active path: ['RD: 1.2.12.2:91 mac-ip 507c.6f4a.d5c6']```

**Comment by carl-baillargeon** [comment]
Hi @Gandalf2110,

Thanks for reporting this. Can you share the output of `show bgp evpn route-type mac-ip | json` and the catalog inputs for the `VerifyEVPNType2Route` test you are using please? You can also share the output of `show bgp evpn route-type mac-ip 507c.6f4a.d5c6 vni <vni>`.

You can use online Pastebin if needed.

Thanks

**Comment by Gandalf2110** [comment]
Hi @carl-baillargeon,

Thank you for response.

Here is catalog test:

`---
anta.tests.routing:
  bgp:
    - VerifyBGPPeersHealth:
        address_families:
          - afi: "evpn"
        filters:
          tags: ['leaf', 'spine', 'gateway']
    - VerifyEVPNType2Route:
        vxlan_endpoints:
          - address: 02f4.c800.0094
            vni: 11
          - address: 507c.6f4a.d5c6
            vni: 91
        filters:
          tags: ['leaf']`
          
 
And here is output of command "show bgp evpn route-type mac-ip 507c.6f4a.d5c6 vni 91 | json" from a VTEP that holds local mac entry 507c.6f4a.d5c6:
 
`{
    "vrf": "default",
    "routerId": "1.2.12.1",
    "asn": 100,
    "evpnRoutes": {
        "RD: 1.2.12.1:91 mac-ip 507c.6f4a.d5c6": {
            "totalPaths": 1,
            "routeKeyDetail": {
                "mac": "507c.6f4a.d5c6",
                "domain": "local",
                "rd": "1.2.12.1:91",
                "nlriType": "mac-ip"
            },
            "evpnRoutePaths": [
                {
                    "nextHop": "2.2.12.12",
                    "asPathEntry": {
                        "asPathType": "Local",
                        "asPath": "i"
                    },
                    "reasonNotBestpath": "noReason",
                    "routeType": {
                        "active": true,
                        "atomicAggregator": false,
                        "backup": false,
                        "ecmp": false,
                        "ecmpContributor": false,
                        "ecmpHead": false,
                        "localAgg": false,
                        "origin": "Igp",
                        "queued": false,
                        "stale": false,
                        "suppressed": false,
                        "valid": true,
                        "waitForConvergence": false,
                        "unknownMetric": false
                    },
                    "weight": 0
                }
            ]
        },
        "RD: 1.2.12.2:91 mac-ip 507c.6f4a.d5c6": {
            "totalPaths": 3,
            "routeKeyDetail": {
                "mac": "507c.6f4a.d5c6",
                "domain": "local",
                "rd": "1.2.12.2:91",
                "nlriType": "mac-ip"
            },
            "evpnRoutePaths": [
                {
                    "nextHop": "2.2.12.12",
                    "asPathEntry": {
                        "asPathType": "Internal",
                        "asPath": "i"
                    },
                    "reasonNotBestpath": "noReason",
                    "routeType": {
                        "active": false,
                        "atomicAggregator": false,
                        "backup": false,
                        "ecmp": false,
                        "ecmpContributor": false,
                        "ecmpHead": false,
                        "localAgg": false,
                        "origin": "Igp",
                        "queued": false,
                        "stale": false,
                        "suppressed": false,
                        "valid": false,
                        "waitForConvergence": false,
                        "unknownMetric": false
                    },
                    "localPreference": 100,
                    "weight": 0
                },
                {
                    "nextHop": "2.2.12.12",
                    "asPathEntry": {
                        "asPathType": "Internal",
                        "asPath": "i"
                    },
                    "reasonNotBestpath": "noReason",
                    "routeType": {
                        "active": false,
                        "atomicAggregator": false,
                        "backup": false,
                        "ecmp": false,
                        "ecmpContributor": false,
                        "ecmpHead": false,
                        "localAgg": false,
                        "origin": "Igp",
                        "queued": false,
                        "stale": false,
                        "suppressed": false,
                        "valid": false,
                        "waitForConvergence": false,
                        "unknownMetric": false
                    },
                    "localPreference": 100,
                    "weight": 0
                },
                {
                    "nextHop": "2.2.12.12",
                    "asPathEntry": {
                        "asPathType": "Internal",
                        "asPath": "i"
                    },
                    "reasonNotBestpath": "noReason",
                    "routeType": {
                        "active": false,
                        "atomicAggregator": false,
                        "backup": false,
                        "ecmp": false,
                        "ecmpContributor": false,
                        "ecmpHead": false,
                        "localAgg": false,
                        "origin": "Igp",
                        "queued": false,
                        "stale": false,
                        "suppressed": false,
                        "valid": false,
                        "waitForConvergence": false,
                        "unknownMetric": false
                    },
                    "localPreference": 100,
                    "weight": 0
                }
            ]
        }
    }
}`

**Comment by carl-baillargeon** [comment]
Hi @Gandalf2110,

Thanks for the output. Let me break down what's happening here:

In the shown output, you're learning the same mac-ip route from two different switches, identified by their RDs:

1. RD 1.2.12.1:91
- This is your local VTEP (matches the router-id)
- Shows asPathType as "Local"
- Passes the test because it has an active/valid path
- This is expected behavior for locally learned routes

2. RD 1.2.12.2:91
- This appears to be an iBGP peer
- Shows asPathType as "Internal"
- Currently failing the test because all 3 paths are inactive/invalid
- This is actually normal behavior since the local route is preferred over iBGP routes

The current test implementation has a flaw: it's checking for at least one active/valid path for EACH learned mac-ip route from EVERY RD. This is incorrect because it's perfectly normal and expected to have multiple switches in your network advertising the same mac-ip, with only one path being active.

I'll update the code to implement the correct logic: checking if we have at least one active/valid path across all learned routes from all RDs combined, rather than requiring active paths for each RD.

Thank you for bringing this to our attention.
